import React, { useState } from 'react';
import { Shield, FileText, ChevronLeft } from 'lucide-react';

interface LegalProps {
    onBack?: () => void;
}

export const Legal: React.FC<LegalProps> = ({ onBack }) => {
    const [activeTab, setActiveTab] = useState<'terms' | 'privacy'>('terms');

    const termsContent = `
# Terms of Service
**Last Updated: December 22, 2025**

Welcome to PromptCore. These Terms of Service ("Terms") govern your access to and use of the PromptCore website and services (the "Service"). By using the Service, you agree to be bound by these Terms.

## 1. Description of Service
PromptCore provides an AI-powered platform for prompt engineering and batch generation of AI content.

## 2. User Accounts
To access certain features, you must create an account via Google Authentication (Supabase Auth). You are responsible for maintaining the security of your account.

## 3. Subscriptions and Credits
- **Credits**: Users can purchase credit packs. Credits are non-refundable and do not expire unless your account is closed.
- **Subscriptions**: We offer monthly subscription plans. You may cancel at any time, but no refunds will be provided for partial months.
- **Payments**: All payments are processed securely via Stripe.

## 4. Acceptable Use
You agree not to:
- Use the Service for any illegal or unauthorized purpose.
- Attempt to hack, destabilize, or bypass credit limits of the Service.
- Use the Service to generate prohibited content as defined by our AI providers (Google Gemini).

## 5. Intellectual Property
PromptCore owns the Service, logo, and platform design. You own the prompts and content generated by your account while using the Service.

## 6. Limitation of Liability
PromptCore is provided "as is" without warranty of any kind. We are not liable for any damages resulting from your use of the Service or any inaccuracies in AI-generated output.

## 7. Changes to Terms
We reserve the right to modify these Terms at any time. Your continued use of the Service constitutes acceptance of the new Terms.

## 8. Contact Us
For any questions regarding these Terms, please contact joe@curiouscoreai.app.
`;

    const privacyContent = `
# Privacy Policy
**Last Updated: December 22, 2025**

At PromptCore, we respect your privacy. This Privacy Policy explains how we collect, use, and protect your information.

## 1. Information We Collect
- **Profile Data**: When you sign in with Google, we collect your name, email address, and profile picture.
- **Usage Data**: We track credit usage and generated prompt history to provide the Service.
- **Payment Data**: We do **not** store your credit card info. All payments are handled by Stripe. We only store your Stripe Customer ID for billing purposes.

## 2. How We Use Your Information
- To provide and maintain the Service.
- To manage your account and subscriptions.
- To communicate with you regarding updates or support.

## 3. Third-Party Services
We use the following third-party providers:
- **Supabase**: For database and authentication.
- **Stripe**: For payment processing.
- **Google Gemini API**: For AI content generation (we do not share your personal info with Google, only the prompt text you provide).

## 4. Security
We implement industry-standard security measures (including Supabase Row Level Security) to protect your data.

## 5. Your Rights
Depending on your location, you may have the right to:
- Access the data we hold about you.
- Request deletion of your account and data.

## 6. Changes to This Policy
We may update this policy from time to time. We will notify users of any significant changes.

## 7. Contact Us
If you have questions about your privacy, please contact joe@curiouscoreai.app.
`;

    return (
        <div className="flex-1 h-full flex flex-col bg-dark-950 text-gray-100 p-4 md:p-8 overflow-y-auto">
            <div className="max-w-4xl mx-auto w-full space-y-8 pb-12">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-brand-600/20 text-brand-500 rounded-lg flex items-center justify-center">
                            <Shield size={24} />
                        </div>
                        <div>
                            <h1 className="text-2xl font-bold text-white">Legal Information</h1>
                            <p className="text-sm text-gray-500">Terms, Privacy, and Compliance</p>
                        </div>
                    </div>
                    {onBack && (
                        <button
                            onClick={onBack}
                            className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors"
                        >
                            <ChevronLeft size={16} /> Back
                        </button>
                    )}
                </div>

                <div className="flex gap-4 border-b border-dark-800">
                    <button
                        onClick={() => setActiveTab('terms')}
                        className={`pb-4 px-2 text-sm font-medium transition-all ${activeTab === 'terms' ? 'text-brand-500 border-b-2 border-brand-500' : 'text-gray-500 hover:text-gray-300'}`}
                    >
                        Terms of Service
                    </button>
                    <button
                        onClick={() => setActiveTab('privacy')}
                        className={`pb-4 px-2 text-sm font-medium transition-all ${activeTab === 'privacy' ? 'text-brand-500 border-b-2 border-brand-500' : 'text-gray-500 hover:text-gray-300'}`}
                    >
                        Privacy Policy
                    </button>
                </div>

                <div className="prose prose-invert max-w-none bg-dark-900/50 border border-dark-800 rounded-2xl p-8 shadow-xl">
                    <pre className="whitespace-pre-wrap font-sans text-gray-300 text-sm leading-relaxed">
                        {activeTab === 'terms' ? termsContent : privacyContent}
                    </pre>
                </div>

                <div className="text-center text-xs text-gray-600">
                    For any legal inquiries, please contact <a href="mailto:joe@curiouscoreai.app" className="underline text-brand-500">joe@curiouscoreai.app</a>
                </div>
            </div>
        </div>
    );
};
